#!/usr/bin/env bash
# `make hooks`: enable the pre-push gate for this clone (ADR-0056).
#
# The forwarders live in the repository's common dir — shared by every linked worktree — and
# core.hooksPath points there absolutely. Each forwarder delegates to the checked-out tree's
# scripts/ci/hook_chain.sh when that exists, and otherwise chains straight to the previous
# hooks, so no checkout of this repo — any worktree, any commit, a bisect step, a hotfix off
# an old tag — is ever left with zero hooks.
set -Eeuo pipefail

common=$(git rev-parse --git-common-dir)
case "$common" in
	/*) ;;
	*) common="$(git rev-parse --show-toplevel)/$common" ;;
esac
common=$(cd "$common" && pwd -P)
dir=$common/jev-hooks
mkdir -p "$dir"

cat >"$dir/jev-hook-delegator" <<'DELEG'
#!/usr/bin/env bash
# Generated by scripts/ci/install_hooks.sh (`make hooks`) — regenerate there, not here.
# Delegates to the checked-out tree's hook chain when it carries one; otherwise chains
# straight to the previous hooks, so no checkout of this repo runs zero hooks (ADR-0056).
set -Eeuo pipefail
name=$(basename "$0")
here=$(cd "$(dirname "$0")" && pwd -P)
top=$(git rev-parse --show-toplevel 2>/dev/null || true)
if [ -n "$top" ] && [ -x "$top/scripts/ci/hook_chain.sh" ]; then
	exec bash "$top/scripts/ci/hook_chain.sh" "$name" "$@"
fi
# Straight chain, the same resolution as scripts/ci/hook_chain.sh minus the gate: global
# (XDG included), then system, then the repo's own .git/hooks; never this directory.
prev_dir=""
for scope in --global --system; do
	if p=$(git config --type path --includes "$scope" core.hooksPath 2>/dev/null) && [ -n "$p" ]; then
		prev_dir=$p
		break
	fi
done
if [ -z "$prev_dir" ]; then
	common=$(git rev-parse --git-common-dir)
	case "$common" in
		/*) ;;
		*) common="$(git rev-parse --show-toplevel 2>/dev/null || echo .)/$common" ;;
	esac
	prev_dir="$common/hooks"
fi
prev_dir=$(cd "$prev_dir" 2>/dev/null && pwd -P) || prev_dir=""
if [ -z "$prev_dir" ] || [ "$prev_dir" = "$here" ]; then
	exit 0
fi
prev_hook=$prev_dir/$name
if [ ! -x "$prev_hook" ]; then
	exit 0
fi
exec "$prev_hook" "$@"
DELEG
chmod 755 "$dir/jev-hook-delegator"

# One forwarder per client-side hook name in githooks(5), except reference-transaction: it
# fires on every ref transaction — client side too — and a forwarder there costs one bash
# spawn per ref update for no gate value, so it is excluded on purpose (ADR-0056).
for name in applypatch-msg pre-applypatch post-applypatch pre-commit pre-merge-commit \
	prepare-commit-msg commit-msg post-commit pre-rebase post-checkout post-merge pre-push \
	pre-auto-gc post-rewrite sendemail-validate fsmonitor-watchman p4-changelist \
	p4-prepare-changelist p4-post-changelist p4-pre-submit post-index-change; do
	ln -sf jev-hook-delegator "$dir/$name"
done

git config core.hooksPath "$dir"

# Prove the gate is reachable through the new hooksPath: with empty stdin nothing is
# checked, but the gate's banner must appear. No flag or variable skips the checks.
out=$(git hook run pre-push -- origin "$(git config --get remote.origin.url 2>/dev/null || echo no-remote)" </dev/null 2>&1) || true
if ! printf '%s\n' "$out" | grep -q "\[pre-push\]"; then
	printf '%s\n' "$out"
	echo "make hooks: core.hooksPath does not reach the pre-push gate" >&2
	exit 1
fi
echo "hooks: enabled — core.hooksPath=$dir, pre-push gate reachable, previous hooks chained"
